language: python
python:
- "3.6"

install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database STORE_DB;' -U postgres
script:
- pytest --cov=storemanager/api/v2

after_success:
- coveralls
- codeclimate-test-reporter